import React, { useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import Mint from '../components/mint';
import List from '../components/list';
import Rent from '../components/rent';

const Home = () => {
  const [showList, setShowList] = useState(false);
  const [rentit, setRentit] = useState(false);

  function handleListClick() {
    setShowList(true);
  }

  function handleRentClick() {
    setRentit(true);
  }

  return (
    <div>
      <Head>
        <title>RevPass</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="" rel="icon" />
      </Head>

      <main className="h-screen bg-gradient-to-br from-white to-orange-900 font-mono">
        <header className="flex justify-end">
          <div className='mr-[15%] text-4xl mt-[1%]'>
            <h1>RevPass</h1>
          </div>
          <div className="mr-[5%] mt-[1%]">
            <ConnectButton accountStatus={"full"}/>
          </div> 
        </header>
        <div className="bg-orange-800 mr-[20%] ml-[20%] flex justify-center text-white border rounded-lg mt-[5%]">
          Welcome to Revpass!
        </div>
        <div className="flex justify-center mt-[5%]">
        <div className="mr-[8%] bg-white px-5 py-3 border rounded-xl hover:bg-blue-600 border-black">
          <Mint />
        </div>
        <div className="mr-[15%]">
        <List />
        </div> 
        <div className="mr-[2%] bg-white px-5 py-3 border rounded-xl hover:bg-blue-600 border-black"> 
        <Rent />
        </div>
        </div>
      </main>
    </div>
  );
};

export default Home;